on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mysqldb
          MYSQL_USER: animzor
          MYSQL_PASSWORD: mega44secret
          MYSQL_ROOT_PASSWORD: mega44rsecret
        ports:
        - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Verify DB connection
        env:
          PORT: ${{ job.services.mysqldb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        env:
          database.password: mega44secret
      - name: Build and test
        run: ./mvnw clean package
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t rag-app-backend .
          docker tag rag-app-backend animzor/rag-app-backend
          docker push animzor/rag-app-backend
